### ISSUE TITLE
Syntax not working

### ISSUE THREAD

**Issue by joaocosta-azores** [xk0der/vscode-postman-collection-syntax#1]
Hello,

Syntax is not working. Currenly using VSC 1.54.3 and extension 0.2.1.

**Comment by xk0der** [comment]
Hey @jonnydevv 👋 

I did not see any issues on my local machine when opening Postman Collection JSON files.
I'm using VSCode `v1.54.3` and Postman Collection Syntax Highlighter v0.2.1 running on MacOS BigSur

Would you be able to share the exported collection JSON that is not getting highlighted properly so that I can test?

**Comment by xk0der** [comment]
Closing this out! Do feel free to log a new issue if the problem reappears 👍
